"""Initial schema

Revision ID: a24ef54834d1
Revises:
Create Date: 2025-04-21 23:15:16.300622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a24ef54834d1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_buildings_id"), "buildings", ["id"], unique=False)
    op.create_index(op.f("ix_buildings_name"), "buildings", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cameras_id"), "cameras", ["id"], unique=False)
    op.create_index(op.f("ix_cameras_name"), "cameras", ["name"], unique=False)
    op.create_table(
        "anomaly_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id", "start_time"),
    )
    op.create_index(
        op.f("ix_anomaly_events_end_time"), "anomaly_events", ["end_time"], unique=False
    )
    op.create_index(
        op.f("ix_anomaly_events_id"), "anomaly_events", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_anomaly_events_start_time"),
        "anomaly_events",
        ["start_time"],
        unique=False,
    )
    op.execute("SELECT create_hypertable('anomaly_events', 'start_time');")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_anomaly_events_start_time"), table_name="anomaly_events")
    op.drop_index(op.f("ix_anomaly_events_id"), table_name="anomaly_events")
    op.drop_index(op.f("ix_anomaly_events_end_time"), table_name="anomaly_events")
    op.drop_table("anomaly_events")
    op.drop_index(op.f("ix_cameras_name"), table_name="cameras")
    op.drop_index(op.f("ix_cameras_id"), table_name="cameras")
    op.drop_table("cameras")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_buildings_name"), table_name="buildings")
    op.drop_index(op.f("ix_buildings_id"), table_name="buildings")
    op.drop_table("buildings")
    # ### end Alembic commands ###
