name: Lint

on:
  push:
  pull_request:

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
    - name: Super-Linter
      uses: super-linter/super-linter@v7.3.0
